### ISSUE TITLE
GTM page view trigger

### ISSUE THREAD

**Issue by sumit-matic** [mzuccaroli/angular-google-tag-manager#10]
If I have setup page view trigger from GTM like image below. Then do I need to push it explicitly from my code too like 
this.router.events.forEach(item => {
  if (item instanceof NavigationEnd) {
    const gtmTag = {
      event: 'page',
      pageName: item.url
    };
    this.gtmService.pushTag(gtmTag);
  }
});
![image](https://user-images.githubusercontent.com/61645966/77996352-7f5a1c80-733e-11ea-8cd3-a4af57d69e33.png)

**Comment by mzuccaroli** [comment]
yes if you want track every instance of navigation event that's the way
