### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by chuhancheng** [mzuccaroli/angular-google-tag-manager#100]
Since our project upgrade to angular 13. Jest test will report `Unexpected value 'GoogleTagManagerModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.`

**Comment by mzuccaroli** [comment]
I'm working on angular 13 support, i hope to release it soon

**Comment by chuhancheng** [comment]
It's great news. Many thanks.

**Comment by mzuccaroli** [comment]
support for angular 13 is releaser with v 1.4.3
https://www.npmjs.com/package/angular-google-tag-manager/v/1.4.3

**Comment by chuhancheng** [comment]
Hi @mzuccaroli ,
Thanks for your work.
I notice that peerDependencies of @angular/common version is still 12.0.3. Did I misunderstand something? 

Because it report ERR when I install 1.4.3 version.
`
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.3" from angular-google-tag-manager@1.4.3
`

**Comment by mzuccaroli** [comment]
thanks I will check it  asap

**Comment by mzuccaroli** [comment]
I  released a 1.4.4 hotfix thank you

**Comment by maxisam** [comment]
IMHO, I think we should bump the major version. I think it introduces breaking change. Our Jest unit test tells us there is a module issue. Also I have couple OSS libraries, people told me it doesn't work with v12.
