### ISSUE TITLE
Multiple gtm.js loaded

### ISSUE THREAD

**Issue by chuhancheng** [mzuccaroli/angular-google-tag-manager#107]
If we continuously call pushTag many time before js loaded. It would cause multiple js loading and these async js loading would cause race condition let our event order incorrect.

**Comment by mzuccaroli** [comment]
i think you have some issues in the library initialization 
did you followed this tutorial? https://itnext.io/how-to-add-google-tag-manager-to-an-angular-application-fc68624386e2
can you provide some code snippets of your configuration?

**Comment by chuhancheng** [comment]
If we call `this.gtmService.pushTag` two times after app initialized.
<img width="603" alt="Screen Shot 2021-12-20 at 2 47 41 PM" src="https://user-images.githubusercontent.com/4800154/146723757-2fa44ce8-72ba-4862-a93e-bfda943017ba.png">

This code would lead addGtmToDom be called two times and then `doc.createElement` would possibly be trigger two times. so that there would have two js be loaded.

**Comment by mzuccaroli** [comment]
the problem is in the push tag function , you don't need to use the add gtm to dom it like  that, take a look to [this tutorial](https://itnext.io/how-to-add-google-tag-manager-to-an-angular-application-fc68624386e2)
or to the demo application included in the repositopry: https://github.com/mzuccaroli/angular-google-tag-manager/blob/master/demo-application/src/app/app.component.ts

**Comment by chuhancheng** [comment]
I had provide a sample PR. Currently we have to check whether GTMscript has loaded before we send another event.

**Comment by phatyh** [comment]
hi @chuhancheng its my solution;

my gtm service code;

```
async send(event: string = 'pageView', data: IData): Promise<void> {
    const gtmTag = {
      event,
      ...data
    };

    await this.gtmService.pushTag(gtmTag);
  }
```


any trigger

`this.gtmService.pageView({pageName: event.url});`

**Comment by phatyh** [comment]
hi @chuhancheng its my solution;

my gtm service code;

```
customEvent(data: IData): void {
  this.send('customEvent', data);
}

pageView(data: IData): void {
  this.send('pageView', data);
}

async send(event: string = 'pageView', data: IData): Promise<void> {
    const gtmTag = {
      event,
      ...data
    };

    await this.gtmService.pushTag(gtmTag);
  }
```

any trigger

`this.gtmService.pageView({pageName: event.url});`


other any trigger
```
this.gtmService.customEvent({
  data,
});
```

**Comment by chuhancheng** [comment]
> hi @chuhancheng its my solution;
> 
> my gtm service code;
> 
> ```
> customEvent(data: IData): void {
>   this.send('customEvent', data);
> }
> 
> pageView(data: IData): void {
>   this.send('pageView', data);
> }
> 
> async send(event: string = 'pageView', data: IData): Promise<void> {
>   const gtmTag = {
>     event,
>     ...data
>   };
> 
>   await this.gtmService.pushTag(gtmTag);
> }
> ```
> 
> any trigger
> 
> `this.gtmService.pageView({pageName: event.url});`
> 
> other any trigger
> 
> ```
> this.gtmService.customEvent({
>   data,
> });
> ```
> 
> hi @mzuccaroli , i think update doc. btw thx to package.
> 
> thx.

Thanks.

**Comment by candidJ** [comment]
I ran into same issue as well. Did the solution work for you @chuhancheng ?

**Comment by candidJ** [comment]
hey @mzuccaroli , any solution or workaround for the problem. I went through the tutorial only to find out multiple tags loaded in demo image. Kindly refer attached. 
<img width="1726" alt="Screenshot 2022-03-14 at 11 35 00 PM" src="https://user-images.githubusercontent.com/12777315/158234280-f8466e40-16b5-4e20-836e-9641d2f61c1c.png">

**Comment by korneliusz-w** [comment]
Just do in constructor on onInit hook more addTag.push and GTM.js will load many times.

`  ngOnInit() {
    const gtmTag = {
      event: 'button-click',
      data: 'my-custom-event',
    };
    this.gtmService.pushTag(gtmTag);

    const gtmTag2 = {
      event: 'button-click2',
      data: 'my-custom-event',
    };
    this.gtmService.pushTag(gtmTag2);`

![image](https://user-images.githubusercontent.com/4181722/164417086-fae4bd0f-367e-45a4-9ff7-9d2ee59098c8.png)

**Comment by paolostefan** [comment]
@mzuccaroli if this isn't a real issue, shouldn't it be closed?
