### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by logularjason** [mzuccaroli/angular-google-tag-manager#111]
Thanks for this module.  I've installed using npm, followed the tutorial, and looked at the source code including demo.

My app.component.ts looks like this:

```
import { Component } from '@angular/core';
import { MatSpinner } from '@angular/material/progress-spinner';
import { TranslateService } from '@ngx-translate/core';
import { GoogleTagManagerService } from 'angular-google-tag-manager'
import moment from 'moment';
import { NGXLogger } from 'ngx-logger';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {

  title: string;
  matSpinner = MatSpinner;

  constructor(
    translator: TranslateService,
    private gtmService: GoogleTagManagerService,
    log: NGXLogger) {

    log.info('Starting application');
    translator.setDefaultLang('en');

    // Globally initialize Moment.js to use the browser locale for date/time formatting.
    moment.locale(navigator.language);
    log.debug(`Configured Moment.js with formatting for ${navigator.language}`);

    translator.get('appName').subscribe(appName => this.title = appName);

    // Initialise google tag manager
    // this.gtmService.addGtmToDom();
  }
}
```
But the build errors with the following that flags a non-EcmaScript module.  I am not sure if this is an issue with the latest release.  

```
Error: ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 139:30-52
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)
```

**Comment by logularjason** [comment]
Also, I have tried both approaches documented in README.md for `app.module.ts` (i.e. I tried both the import and also provider)

**Comment by mzuccaroli** [comment]
Hi @logularjason which version of angular are you using?

**Comment by logularjason** [comment]
Hi Marco!!

Version 11.2.

    "@angular/animations": "^11.2.14",
    "@angular/cdk": "^11.2.9",
    "@angular/common": "^11.2.0",
    "@angular/compiler": "^11.2.0",
    "@angular/core": "^11.2.0",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "^11.2.0",
    "@angular/google-maps": "^11.2.9",
    "@angular/material": "^11.2.9",
    "@angular/material-moment-adapter": "^11.2.9",
    "@angular/platform-browser": "^11.2.0",
    "@angular/platform-browser-dynamic": "^11.2.0",
    "@angular/router": "^11.2.0",
    "@angular/service-worker": "^11.2.10",

**Comment by logularjason** [comment]
In researching the error, it looks like angular webpack has trouble with the mjs files in the module, and the work-around is to use custom webpack config to mark mjs files as javascript.

We are using the custom-webpack module below:

https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-object

I configured it with the clause below, and the errors are gone now.  Unclear to me why I experience this issue and not other users of the module?

```
  module: {
    rules: [
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: "javascript/auto"
      }
    ]
  }
```

**Comment by logularjason** [comment]
Although the webpack config above eliminated the compile errors, at runtime I get this exception:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'Injectable')
    at Module.Tr5K (angular-google-tag-manager.mjs:89)
    at __webpack_require__ (bootstrap:84)
    at Module.ARii (app.component.ts:2)
    at __webpack_require__ (bootstrap:84)
    at Module.f8Qc (app.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module.KBBS (site.reducer.ts:382)
    at __webpack_require__ (bootstrap:84)
    at Object.0 (tag-history.module.ts:28)
    at __webpack_require__ (bootstrap:84)
```

Looks like it cannot resolve Injectable - this is the offending line of code:

`GoogleTagManagerService.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "13.1.1", ngImport: i0, type: GoogleTagManagerService, deps: [{ token: 'googleTagManagerConfig', optional: true }, { token: 'googleTagManagerId', optional: true }, { token: 'googleTagManagerAuth', optional: true }, { token: 'googleTagManagerPreview', optional: true }, { token: 'googleTagManagerResourcePath', optional: true }, { token: 'googleTagManagerCSPNonce', optional: true }], target: i0.ɵɵFactoryTarget.Injectable });`

**Comment by mzuccaroli** [comment]
latest released is optimized for angular 13, for angular 11 you can safely use an old version, the target release is 1.3.x so you can try
`npm i angular-google-tag-manager@1.3.2`
