### ISSUE TITLE
Does this support injection of other scripts?

### ISSUE THREAD

**Issue by alessandroderoma** [mzuccaroli/angular-google-tag-manager#112]
Does the plugin support injection of facebook pixel or other scripts as shown [here](https://www.analyticsmania.com/post/facebook-pixel-with-google-tag-manager/)?

Is there any specific way to configure it?

**Comment by mzuccaroli** [comment]
of couse, handle this kind of scripts without change and re-deploy the main codebase is the main purpose of google tag manager
