### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by uladzimir-miadzinski** [mzuccaroli/angular-google-tag-manager#116]
Hi, could you help me with what should I do if I need to use Google Tag Manager only on specific pages?

Imagine our application: 

- it has two envs: dev and prod
- prod env has two types of pages: 

1. Exposed to the internet as FREE pages without authorization
2. Not exposed to the internet that requires user authorization
3. These pages are the same components and modules. The difference is only in the authorization mechanism before the user sees them.

- the requirement is to have Google Tag Manager with CookieBot only on FREE pages
- should not display any cookie consent messages for authorized users

Can I do this using your library? As I see we should add 
```
GoogleTagManagerModule.forRoot({
      id: YOUR_GTM_ID,
    })
```
in root app module. 

Does it mean that the GTM script will be injected into the whole application by default without any possibility for us to control on what page we need it? Are there any options to choose somehow that the GTM script should be only when a user comes to a FREE content page? 

Thank you

**Comment by mzuccaroli** [comment]
i think that you can solve this by configuring your tag in google tag manager console,
generally the best solution is to have gtm in all your pages ad activate/deactivate tags (for example you dont want cookie bot on authorized pages but you may want other tags like analytics)

angular is a single page application so the gtm script is loaded once at the first load, activating/deactivating tags it's somethig you control in your gtm console, you can take a look here: https://www.nichemarket.co.za/blog/nichemarket-advice/fire-gtm-multiple-unique-pages
or here: https://www.simoahava.com/analytics/trigger-guide-google-tag-manager/
