### ISSUE TITLE
ES5 Compatibility for IE

### ISSUE THREAD

**Issue by maguilarl** [mzuccaroli/angular-google-tag-manager#119]
Hi, I have a question.

When I run my application prepared to be compatible with IE 11 I get errors that come from this library. To make the application compatible to run in IE I follow the steps in the following link: https://dev.to/coly010/angular-how-to-support-ie11-4924 . It works and I see the content in IE. The problem comes when I add this library.
My question is if this library is compatible to run with ES5?

Thank you.

**Comment by mzuccaroli** [comment]
wich version of the library are you using? recent versions require angular 13 and I dont think support old browsers

**Comment by maguilarl** [comment]
I am using version 1.4.2

**Comment by mzuccaroli** [comment]
you can try older versions but theres no warranty of ie support
