### ISSUE TITLE
The script of google tag manager should be inside the header tag and not outside of it

### ISSUE THREAD

**Issue by sbetan10** [mzuccaroli/angular-google-tag-manager#13]
Hi, 
i'm using Angular 9 and the 1.1.1 versión of angular-google-tag-manager; when inspect the source code of the application, the script of GTM its outside of the header tag. why it happens? 

Shoult be inside the tag header like recommends the oficial page Google.

Thank

**Comment by mzuccaroli** [comment]
it should be inside the header, 
the main logic add the script before the header first child, do you have some strange tags in your code or a empty header?

**Comment by mzuccaroli** [comment]
closing due to lack of responses
