### ISSUE TITLE
Custom HTML Error

### ISSUE THREAD

**Issue by tibinvpaul** [mzuccaroli/angular-google-tag-manager#130]
Hello,

I have `Google Analytics: Universal Analytics` and another pixel in my tag manager account. The second tag has the type `Custom HTML`. It is triggering a `custom event`, and the name is `pageview`. The script looks like the below.

```
<!-- begin Widget Tracker Code -->
<script>
(function(w,i,d,g,e,t){w["WidgetTrackerObject"]=g;(w[g]=w[g]||function()
{(w[g].q=w[g].q||[]).push(arguments);}),(w[g].ds=1*new Date());(e="script"),
(t=d.createElement(e)),(e=d.getElementsByTagName(e)[0]);t.async=1;t.src=i;
e.parentNode.insertBefore(t,e);})
(window,"https://widgetbe.com/agent",document,"widgetTracker");
window.widgetTracker("create", "******");
window.widgetTracker("send", "pageview");
</script>
<!-- end Widget Tracker Code -->
```

The app is sending events for the first load and immediate route change. After that, I am getting an error as follows.

![fub_pixel](https://user-images.githubusercontent.com/2771721/162575935-ab486d8d-8279-4173-bf73-5faff3a73d69.png)

When I disable the second pixel (Custom HTML one), there is no error. I am having a hard time identifying whether the issue is due to the pixel script OR the package. The implementation is as per the documentation.

Can someone help me here to identify the issue?

**Comment by mzuccaroli** [comment]
I think the error is caused the custom pixel, the library only add the the scripts to enable GTM.
It seems that the custom event that your code generates causes some trouble to universasl analytics.
