### ISSUE TITLE
Using 2 tags

### ISSUE THREAD

**Issue by ujfator** [mzuccaroli/angular-google-tag-manager#137]
Hi, is there a possibility of using two tags? Customer now has UA tag and wants to use GA4 tag alongside it for some time. Thank you.

**Comment by mzuccaroli** [comment]
i think you can manage it inside the tag manager account, you can load multiple tags there

**Comment by ujfator** [comment]
Thanks for a quick reply, and how will the library know about the second tag? If I provide only one in setup as this ` {
            provide: 'googleTagManagerId',
            useValue: 'GTM-XXX11X',
        },` and new G4A tag will have different id?

**Comment by mzuccaroli** [comment]
you need to configure that inside GTM, i'ts not a code issue but a gootle tag manager configuration issue,
take a look at that:
https://searchengineland.com/how-to-set-up-google-analytics-4-using-google-tag-manager-374584
https://www.analyticsmania.com/post/how-to-install-google-analytics-4-with-google-tag-manager/
