### ISSUE TITLE
Send User ID after Login

### ISSUE THREAD

**Issue by sappolanco** [mzuccaroli/angular-google-tag-manager#138]
Hi, 

I have configured GTM to recieve user id as data layer variable following the next guide 

[https://support.google.com/tagmanager/answer/9442095](url)

I'm able to send it but what I really need is to send it before "Container Loaded" in order to each event that triggers has the user id 

![image](https://user-images.githubusercontent.com/76975860/169405963-db261db3-b68c-47e6-a80c-b2fe88ea7ac2.png)

Thank you

**Comment by mzuccaroli** [comment]
hi, I think this is a GTM internal configuration, I'm sorry but I'm not expert enough to help you, the library only function is to include the gtm required scripts in your angular project and push events to datalayer

**Comment by tyagirajat200** [comment]
Hi  

> Hi,
> 
> I have configured GTM to recieve user id as data layer variable following the next guide
> 
> [https://support.google.com/tagmanager/answer/9442095](url)
> 
> I'm able to send it but what I really need is to send it before "Container Loaded" in order to each event that triggers has the user id
> 
> ![image](https://user-images.githubusercontent.com/76975860/169405963-db261db3-b68c-47e6-a80c-b2fe88ea7ac2.png)
> 
> Thank you

Hi,
I am working on the integration of GA4 using Google Tag Manager. I also want to achieve the save i.e sending custom events and updating the config for userId.
gtm service pushTag is not working.
