### ISSUE TITLE
400 Error when using in live env

### ISSUE THREAD

**Issue by joncorrin** [mzuccaroli/angular-google-tag-manager#14]
I'm using the code below to dynamically add the ID based on a URL. Here is an example of it in use:
https://xilo-dev-forms.herokuapp.com/client-app/form/page/start?companyId=357974&gtagId=GTM-WBJL4SD&agent=ssachdev20%20dev@gmail.com&formId=6

```
main-es2015.18f7e95ce1f60d738dac.js:1 GET https://www.googletagmanager.com/gtm.js?id= net::ERR_ABORTED 400
addGtmToDom @ main-es2015.18f7e95ce1f60d738dac.js:1
pushTag @ main-es2015.18f7e95ce1f60d738dac.js:1

www.googletagmanager.com/ns.html?id=:1 Failed to load resource: the server responded with a status of 400 ()
```

locally all works well and the tag fires. In live environments like staging and develop it fails to append the ID. Youll see below Im dynamically adding the ID but if you look at the console it prints just fine which I assume means it should be passing the the provider correctly. 

Any idea what Im doing wrong? 
```
import { ErrorHandler, NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import {MomentModule} from "angular2-moment";
import { environment } from '../environments/environment';
import { AppComponent } from './app.component';
import { FormMethodService } from './services/form-method.service';
import { UnknownComponent } from './unknown.component';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgxLoadingModule } from 'ngx-loading';
import { FormsModule } from '@angular/forms';

let gtmId = '';

if (window.location.href.toString().includes('gtagId')) {
  const vars = {};
  const parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
    return vars[key] = value;
  });
  gtmId = vars['gtagId'];
  console.log(gtmId);
}

@NgModule({
  declarations: [
      AppComponent,
  ],
  imports: [
      BrowserModule,
      AppRoutingModule,
      HttpClientModule,
],
  providers: [
    {provide: 'googleTagManagerId', useValue: gtmId}  
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by mzuccaroli** [comment]
I think that the source of the problem could be the usage of "window.location.href", global variables are usually messy
have you tried using the angular [ActivatedRoute](https://angular.io/api/router/ActivatedRoute)?

**Comment by joncorrin** [comment]
This is in my app.module file so Im unsure if I can access ActivatedRoute at this point. Is that possible and or smart to do? 

Also, its still logging the correct gtagId. So the variable should be fine

**Comment by joncorrin** [comment]
Just added some more logs and getting same error. I dont think its the window object as its returning true prior to the gtag error: 

Here is what was logged: 
```
GTM-WBJL4SD
main-es2015.932a9cccfc421ae0b4a2.js:1 true "GTM-WBJL4SD"
```

Here us the code
```
let gtmId = '';

if (window.location.href.toString().includes('gtagId')) {
  const vars = {};
  const parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
    return vars[key] = value;
  });
  gtmId = vars['gtagId'];
  console.log(gtmId);
}

console.log(window.location.href.toString().includes('gtagId'), gtmId);
```

**Comment by joncorrin** [comment]
https://xilo-staging-forms.herokuapp.com/client-app/form/page/start?companyId=955987&agent=jon@xilo.io&formId=95&clientId=20505&gtagId=GTM-WBJL4SD

**Comment by joncorrin** [comment]
Do you have any other suggestions on how to make the gtagId dyanmic?

**Comment by mzuccaroli** [comment]
if you build your production code and run it from your dist folder you have the same issue?

also a good (and safer) idea to make your gtmId  dynamic is retrieve it from a dedicated API or a AWS Systems Manager Parameter Store, than leaving it on on query string

**Comment by joncorrin** [comment]
Same error when building in production `ng serve --prod`. When I run ng serve without the --prod flag it works fine. I cant nail down why this is happening.

**Comment by mokipedia** [comment]
you could probably do it with a useFactory function instead of useValue
something like:
`providers: [
    {provide: 'googleTagManagerId', useFactory: () => {
            if (window.location.href.toString().includes('gtagId')) {
            const vars = {};
            const parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, 
            function(m,key,value) {
               return vars[key] = value;
            });
            return vars['gtagId'] || 'SOME_SENSIBLE_DEFAULT_IF_POSSIBLE';
          }
     }  
  ],`
