### ISSUE TITLE
ReferenceError: Cannot access 'GoogleTagManagerConfigService' before initialization

### ISSUE THREAD

**Issue by limitofzero** [mzuccaroli/angular-google-tag-manager#147]
Hello guys! I have a next issue: 

Reproduction: 
https://github.com/limitofzero/angular-tag-manager-error-example

instruction to reproduce:

- git clone https://github.com/limitofzero/angular-tag-manager-error-example
- yarn(or npm install)
- yarn test

Description
I have a service which injects GoogleTagManagerService. Looks like this:

```
import { Inject, Injectable, Optional } from '@angular/core';
import type { Request } from 'express';

import { REQUEST } from './app.tokens';
import { GoogleTagManagerService } from "angular-google-tag-manager";

@Injectable({
  providedIn: 'root',
})
export class AppService {
  constructor(
    @Inject(REQUEST) @Optional() private request: Request,
    private service: GoogleTagManagerService
  ) {}

  public init() {
    this.service.addGtmToDom();
  }
}
```

and a jest test:
```
describe.skip('AppService', () => {
  let service: AppService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(AppService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
```

If I run a test with yarn test I get an error:

ReferenceError: Cannot access 'GoogleTagManagerConfigService' before initialization

<img width="752" alt="image" src="https://user-images.githubusercontent.com/16196664/178047750-8d375138-fff0-4230-8906-fa73bdd83730.png">

Angular version
14.0.4

angular-google-tag-manager version
latest

Which operating systems have you used?
 macOS
 
FIX pr ref #148

**Comment by LittleChloe** [comment]
*bump*

Just want to ask, if any chance the fix can be provided soon? After migration to angular 14, a lot of our tests are failing because of this

**Comment by smichel-amiltone** [comment]
Same here... need a tag with this fix

Thx ;)

**Comment by mzuccaroli** [comment]
version 1.6.1 has been released on NPM https://www.npmjs.com/package/angular-google-tag-manager
thank you for your contribution
