### ISSUE TITLE
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 32:30-36 Can't import the named export 'Inject' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by sandirr** [mzuccaroli/angular-google-tag-manager#149]
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 32:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 140:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 145:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 150:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 155:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 160:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 165:30-36
Can't import the named export 'Inject' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 26:18-28
Can't import the named export 'Injectable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 132:18-28
Can't import the named export 'Injectable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 36:42-56
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 182:18-26
Can't import the named export 'NgModule' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 30:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 138:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 143:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 148:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 153:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 158:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 163:30-38
Can't import the named export 'Optional' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 23:227-245
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 129:483-501
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 178:157-175
Can't import the named export 'ɵɵFactoryTarget' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 25:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 131:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 181:0-27
Can't import the named export 'ɵɵngDeclareClassMetadata' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 23:37-58
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 129:31-52
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 178:30-51
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 24:38-62
Can't import the named export 'ɵɵngDeclareInjectable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 130:32-56
Can't import the named export 'ɵɵngDeclareInjectable' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 180:30-52
Can't import the named export 'ɵɵngDeclareInjector' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/angular-google-tag-manager/fesm2015/angular-google-tag-manager.mjs 179:30-52
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

![image](https://user-images.githubusercontent.com/50796200/180644775-79a3a342-9215-4dd7-bb26-b73c8cad945e.png)

**Comment by sandirr** [comment]
Anyone can help? please!

**Comment by Aishwaryakakade** [comment]
I am experiencing the same issue.

**Comment by mzuccaroli** [comment]
sorry for the late reply but I'm the only mantainer , wich version of the library are you using?

@ToStr1  for angular 11 you must use old version of the library 1.3.X

you can check your angular version and the related release here: https://github.com/mzuccaroli/angular-google-tag-manager/releases
and check the available releases here: https://www.npmjs.com/package/angular-google-tag-manager

**Comment by ToStr1** [comment]
Thanks for the info @mzuccaroli. Using the correct version fixed the issue on my end. Wasn't aware of the compatibility requirements. Thanks a lot :)

**Comment by VamsiKWilco** [comment]
Hi @mzuccaroli ,

I used following versions:
"angular-google-tag-manager": "^1.2.4", and
"angular-google-tag-manager": "^1.6.0"

I'm facing the error, Does this library supports Angular: 8.2.X ?

Kindly let us know.

Thanks in advance,
Vamsi K

**Comment by mzuccaroli** [comment]
No, it has been developed with angular 9, you can try[1.0.0](https://www.npmjs.com/package/angular-google-tag-manager/v/1.0.0) version but officiale support statrs with angular 9

**Comment by VamsiKWilco** [comment]
Version 1.0.0 installed successfully and working as expected.

Thanks @mzuccaroli
