### ISSUE TITLE
Null-Like GTM-ID should not throw an error

### ISSUE THREAD

**Issue by ma7moudat** [mzuccaroli/angular-google-tag-manager#158]
**Background:**
- Our project (much like many others) has different settings for DEV and PROD. We want GTM only for PROD.
- The GoogleTagManagerModule can not be imported conditionally (on for PROD, off for DEV).
- Providing a null-like value (empty string, null, undefined) for `googleTagManagerId` causes an error and breaks the whole application.

This doesn't make much sense, since GTM is not a crucial piece of code and the project should be able to run without it. Kind of an opt-in feature.

This means, when the settings are not valid, an error should not be thrown; maybe just a console warning instead hinting to the facts that tags can't be pushed.

**Comment by AElmoznino** [comment]
Struggling with the same issue here, +1!

**Comment by cmalard** [comment]
works fine with empty string ;-)
