### ISSUE TITLE
Versão 1.1.1 pra frente com problema no build

### ISSUE THREAD

**Issue by leandro-mancini** [mzuccaroli/angular-google-tag-manager#16]
Olá assim que vocês publicaram uma nova versão no npm o projeto que estou trabalhando tem apresentado esse problema na hora do build.

Warning: Can't resolve all parameters for TagService in /app/src/app/data/tag/tag.service.ts: (?, [object Object]). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for TagService in /app/src/app/data/tag/tag.service.ts: (?, [object Object]). This will become an error in Angular v6.x
ERROR in src/app/data/tag/tag.service.ts:4:41 - error TS2307: Cannot find module 'angular-google-tag-manager'.
4 import { GoogleTagManagerService } from 'angular-google-tag-manager';

Estou usando a versão no @angular/cli@^8.3.25 e @angular/core@~8.2.14

![image](https://user-images.githubusercontent.com/8883746/80128958-cbc6ff80-856c-11ea-9b6f-5503c09a7583.png)

**Comment by philly25** [comment]
Got the same today. 
Angular 9.1.3

**Comment by mzuccaroli** [comment]
Please open your issue in english, the version released this morning (1.1.2 and 1.1.3) had ha build problem the just released 1.1.4 shopuld fix it

**Comment by philly25** [comment]
Yes, it works now.

**Comment by mzuccaroli** [comment]
thank you for the feedback
