### ISSUE TITLE
Unable to import angular-google-tag-manager-config.service

### ISSUE THREAD

**Issue by strike2867** [mzuccaroli/angular-google-tag-manager#171]
Error: Can't resolve 'angular-google-tag-manager-config.service' in '...' 
Cannot find module 'angular-google-tag-manager-config.service' or its corresponding type declarations.

It looks as though GoogleTagManagerConfiguration is not exported.

**Comment by pm20390** [comment]
I've fixed this in my fork.

**Comment by lechatgraphique** [comment]
Hi @pm20390,

Thanks for the fix on the import. The time that the modification is pushed, I made the modification on my side but it seems to have another error?

`Error: export 'GoogleTagManagerConfiguration' (imported as 'GoogleTagManagerConfiguration') was not found in 'angular-google-tag-manager' (possibl
e exports: GoogleTagManagerModule, GoogleTagManagerService)
`

public-api.ts 
`
export * from './lib/angular-google-tag-manager.service';
export * from './lib/angular-google-tag-manager.module';
export * from './lib/google-tag-manager-config';
export * from './lib/angular-google-tag-manager-config.service';
`

Best regard

**Comment by pm20390** [comment]
Hi @lechatgraphique

I will double check later but that should be resolved by the last line in your public-api. I am using this currently without issue.

Are you sure you’ve imported GoogleTagManagerConfiguration correctly where you need to use it?

Best

**Comment by lechatgraphique** [comment]
logically it should work.
I show you

public-api.d.ts
![image](https://user-images.githubusercontent.com/49923273/219356683-608ad34b-aa49-450d-a0b1-207d512e8c58.png)

app.module.ts
![image](https://user-images.githubusercontent.com/49923273/219356558-9a8ca077-4914-4aef-8913-56c30fc089e1.png)
![image](https://user-images.githubusercontent.com/49923273/219356422-4afdf35b-cbe1-40ed-8a41-a248198d0931.png)
![image](https://user-images.githubusercontent.com/49923273/219356858-198b3eb9-94a6-440e-bee6-03655879fdc6.png)

**Comment by pm20390** [comment]
If you need this change now, I would use my fork “ng-google-tag-manager” and then just switch back when it gets merged. Editing the .d.ts files for the built output won’t work.

**Comment by lechatgraphique** [comment]
Ok thanks, I will do that  :)

**Comment by lechatgraphique** [comment]
Great thanks for the helping hand. It works damn ;)
