### ISSUE TITLE
Clear the dataLayer

### ISSUE THREAD

**Issue by YouZag** [mzuccaroli/angular-google-tag-manager#176]
I've tried to create a fork - but am failing to make it build properly.  So, I'm resorting to creating a feature request here...

The items array pushes to the array.  However, on new page views, I'd like to refresh that array and push new items to it on an event.

Does this sound correct?  If so, my feature request would be to add a function to clearDataLayer() and be able to fire a fresh event without appending to the same items array.

**Comment by mzuccaroli** [comment]
I think this is not correct , gtm use a single instance of the datalayer for each session an you can push new events/pageviews on it
