### ISSUE TITLE
[feature request] make noscript tag optional (as it makes only sense with angular universal)

### ISSUE THREAD

**Issue by mokipedia** [mzuccaroli/angular-google-tag-manager#18]
As the `<noscript>` tag will probably never be added to the app if the browser does not support javascript in the first place, it might be a good idea to make it configurable if it should add it or not.

That way, if you need it you could at least add the `<noscript>` tag to your index.html hardcoded and not end up with a duplicate in your DOM.

It does make sense for Angular Universal though, as that would render it into the DOM before sending it to the Browser, though.

**Comment by hanstf** [comment]
Hi I am having duplicate as well, how do you fix it ?

**Comment by mzuccaroli** [comment]
I think the solution proposed in [this issue](https://github.com/mzuccaroli/angular-google-tag-manager/issues/36) (that prevent service loading in the prerendered version) may fix it, in the next days I will try it
