### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Maximaximum** [mzuccaroli/angular-google-tag-manager#184]
Hello!

Would you mind releasing a new version that supports Angular 16 please?

Thank you!

**Comment by elena-dev-thought** [comment]
Hi @Yberion are you working on it? Otherwise I could give it try today in the evening. Just want to make sure that there is no one else from the community doing it at the same time.

**Comment by Yberion** [comment]
Hello @elena-dev-thought, I was going to do it yesterday night, but was too tired haha, feel free to do it as on my side I did not start it yet 😃 

I planned to do it tonight, so it's up to you.

**Comment by mattiLeBlanc** [comment]
Thanks guys!

**Comment by Yberion** [comment]
Hello @mzuccaroli, I prefer to ponctually help when I get time ^^

Thanks for the merge tho!

**Comment by mattiLeBlanc** [comment]
Thank you sir!
