### ISSUE TITLE
Youtube video keep emitting gtm.video after navigating away

### ISSUE THREAD

**Issue by mattiLeBlanc** [mzuccaroli/angular-google-tag-manager#187]
Hi

I understand you don't support Google Tagmanager, but do you happen to know why I am seeing gtm.video events emitted to datalayer after leaving my youtube video player page? I am using an Angular 15 project and the component gets destroyed.
Only when I pause the video and than navigate away it seems to stop emitting. But it requires a delay after pause and navigation. 
Really weird.
I am going to try adding GTM manually and see if that makes any difference which it shouldn't.

**Comment by mzuccaroli** [comment]
i think it depends on the component you are using for youtube, the library only recive all avents and push them to the data layer nothing more

**Comment by mattiLeBlanc** [comment]
I have tried bare GTM implementation and bare youtube iframe implementation and the issue persists.
Very strange issue.

**Comment by mzuccaroli** [comment]
yes, i think it really depends on how  youtybe handle playback events,
closing the issue because is not related to the library code
