### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by supermakdas** [mzuccaroli/angular-google-tag-manager#189]
Feature Description
Please add Angular version 17 support.

NPM error log
`
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: angular-google-tag-manager@1.7.0
npm ERR! Found: @angular/common@17.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.0.1" from the root project
npm ERR!   peer @angular/common@"^17.0.0 || ^18.0.0" from @angular/cdk@17.0.0
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^17.0.0" from the root project
npm ERR!     peer @angular/cdk@"17.0.0" from @angular/material@17.0.0
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^17.0.0" from the root project
npm ERR!       1 more (ngx-material-luxon)
npm ERR!   11 more (@angular/forms, @angular/google-maps, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.0.0" from angular-google-tag-manager@1.7.0
npm ERR! node_modules/angular-google-tag-manager
npm ERR!   angular-google-tag-manager@"~1.7.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@15.2.10
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^15.0.0" from angular-google-tag-manager@1.7.0
npm ERR!   node_modules/angular-google-tag-manager
npm ERR!     angular-google-tag-manager@"~1.7.0" from the root project
`

**Comment by mzuccaroli** [comment]
we will add angular 17 support as soon as possible

**Comment by mattiLeBlanc** [comment]
Looking forward to A17 support.

**Comment by gestj** [comment]
Bump... :)

Right now we run with `npm ci --force` in our CI because of this... :/

**Comment by hassanasad** [comment]
As a temporary solution, i am using the npm dependency "overrides" method because `npm ci --force` requires too many changes in the CI/CD pipelines. Hope it helps.

```
"devDependencies": {
	...
	...
},
"overrides": {
	"angular-google-tag-manager": {
		"@angular/animations": "~17.0.0",
		"@angular/common": "~17.0.0",
		"@angular/compiler": "~17.0.0",
		"@angular/core": "~17.0.0",
		"@angular/forms": "~17.0.0"
	}
}
```

**Comment by gestj** [comment]
@hassanasad Wow,  nice. I wasn't aware of that. That's so much better and it works 🥇

**Comment by mattiLeBlanc** [comment]
Can the plugin please be updated? People are relying on it. It is not a big change believe to change the package requirements

**Comment by mzuccaroli** [comment]
we are working on it https://github.com/mzuccaroli/angular-google-tag-manager/pull/190
there are some compatibility issues to be solved

**Comment by gestj** [comment]
> version 1.9.0 with angular 17 support is released many thanks to all contributors

@mzuccaroli  Thanks for your effort!

**Comment by mattiLeBlanc** [comment]
Thank you for your effort kind sir!
