### ISSUE TITLE
Is an angular 18 version on the way ?

### ISSUE THREAD

**Issue by mtabaj** [mzuccaroli/angular-google-tag-manager#197]

**Comment by Khaldor48** [comment]
+1

**Comment by mikila85** [comment]
...

**Comment by mikila85** [comment]
"angular-google-tag-manager-angular-18": "^18.0.0",

**Comment by mikila85** [comment]
even better solution, add this to the end of the package.json:

  "overrides": {
    "angular-google-tag-manager": {
      "@angular/animations": "^18.0.3",
      "@angular/common": "^18.0.3",
      "@angular/compiler": "^18.0.3",
      "@angular/core": "^18.0.3",
      "@angular/forms": "^18.0.3"
    }
  }

**Comment by 5uper** [comment]
+1

**Comment by mattiLeBlanc** [comment]
An  update would be nice. +3

**Comment by guillaume-moreau** [comment]
Hi !

Also in need for this update; I've created a PR: https://github.com/mzuccaroli/angular-google-tag-manager/pull/198

**Comment by mzuccaroli** [comment]
PR has been merged and the library has been published, so many thanks to @guillaume-moreau  for the contrybution

I am so sorry for publishing the new version so late but I'm not working in Angular any more and I'm losing my proficiency on it so i need to rely on the contributors.

If someone is available to become mantainer I'll be so happy for the help!!
