### ISSUE TITLE
The url used is old.

### ISSUE THREAD

**Issue by miradnan** [mzuccaroli/angular-google-tag-manager#22]
Can you update the url used in it? 

It should be https://www.googletagmanager.com/gtag/js?id=UA-XXXXXX-1

**Comment by mzuccaroli** [comment]
hi @miradnan  the url you provided is a **google analytics** (now gtag) and not a **google tag manager** url notice the fact that the id starts with "UA-" and not with "GTM-"
for more info [read this](https://www.analyticsmania.com/post/google-tag-manager-vs-google-analytics/)
