### ISSUE TITLE
make url prefix optional

### ISSUE THREAD

**Issue by zwessels** [mzuccaroli/angular-google-tag-manager#33]
for some reason this fails (404): https://www.googletagmanager.com/gtm.js?id=GTM-ID

but this works: https://googletagmanager.com/gtm.js?id=GTM-ID

can you make the www optional? 

seems like other people also experience the same issue: https://stackoverflow.com/a/50652712/404376

**Comment by mzuccaroli** [comment]
I have checked and now the script is currectly downloaded, I think it was a temporary issue
![Schermata del 2020-09-20 17-33-20](https://user-images.githubusercontent.com/4458254/93715095-6866eb00-fb67-11ea-95b9-d8393e12fbf1.png)
