### ISSUE TITLE
how can I load multiple tags in the same app?  

### ISSUE THREAD

**Issue by roeeovadia** [mzuccaroli/angular-google-tag-manager#34]
how can I load multiple tags in the same app?

**Comment by mzuccaroli** [comment]
If you want to add multiple tags you need to add them in the GTM console, It's a basic configuration of Google tag manager, take a look to the official documentation: https://support.google.com/tagmanager/answer/6106924?hl=en&ref_topic=3002579

However, if you need to run multiple GTM Containers On The Page, you can't use  the library, It's nor a standard usage of gtm neither a best practice (data layer variables can conflict), so if you really need it you should add this feature manually, take a look at this: https://www.simoahava.com/gtm-tips/multiple-gtm-containers-on-the-page/
