### ISSUE TITLE
GoogleTagManagerService static injection error

### ISSUE THREAD

**Issue by SRKnoldus** [mzuccaroli/angular-google-tag-manager#38]
I believe this has been recently updated and this has resulted in some issues in compilation of old Angular Apps like version 8.
The service now needs to be imported in the provider array of the root app module.
![Screenshot from 2020-09-21 19-48-59](https://user-images.githubusercontent.com/46520255/93778475-94f03500-fc43-11ea-9e89-86ea01073922.png)

**Comment by mzuccaroli** [comment]
hi @SRKnoldus yesterday the angular 10 version was released, for angular 8 you need to use [older version](https://www.npmjs.com/package/angular-google-tag-manager/v/1.1.4) :
npm i --save angular-google-tag-manager@1.1.4
