### ISSUE TITLE
Support for GTM environments

### ISSUE THREAD

**Issue by tha022** [mzuccaroli/angular-google-tag-manager#4]
Great lib! Starting using it in our project. 

But, one thing, do you have support for different GTM environments?
https://support.google.com/tagmanager/answer/6311518?hl=en

**Comment by mzuccaroli** [comment]
yes, if the difference in the code snippets is the ID you can handle it via angular environment variables

take a look to this tutorial in the "install and configure section" : https://itnext.io/how-to-add-google-tag-manager-to-an-angular-application-fc68624386e2

when you provide the gtm id you can use an environment variable like:
```

providers: [
  …
  {provide: 'googleTagManagerId', useValue: environment.googleTagManagerId}
],

```
and put different id in different environments

if environment-specific code snippets have other differences i need tho take a deeper look to them

**Comment by mzuccaroli** [comment]
@tha022  I take a look to you article and environment defined in that way are currently not supported 
is't a little tricky to identify and pass the correct variables to insert into the snippet but il'try to figure out

in all project that I contributed we used different containers for different environments and google itself in the article suggest that environments are a non-producrion feature so I'm not sure if 
it's worth it

> The Environments feature is designed for use with non-production environments. To ensure the best performance, you should install the standard Tag Manager container snippet on live/production websites.

**Comment by mzuccaroli** [comment]
gtm environments are now supported with version 1.1.2
