### ISSUE TITLE
Ivy compatibility

### ISSUE THREAD

**Issue by Borongaj** [mzuccaroli/angular-google-tag-manager#44]
Error message displayed in the console :

> This likely means that the library (angular-google-tag-manager/lib/angular-google-tag-manager.module) which declares GoogleTagManagerModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by mzuccaroli** [comment]
have you installed the latest version of the library?

**Comment by Borongaj** [comment]
I installed 1.2.3.

**Comment by marekdon** [comment]
Same problem for me as well

**Comment by juleskreutzer** [comment]
Same on 1.2.4
