### ISSUE TITLE
Support for Angular 11

### ISSUE THREAD

**Issue by TokkeDev** [mzuccaroli/angular-google-tag-manager#46]
angular-google-tag-manager should allow peer dependency of Angular 11. When doing npm install, the following errors appear:
```
npm WARN angular-google-tag-manager@1.2.4 requires a peer of @angular/common@^10.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN angular-google-tag-manager@1.2.4 requires a peer of @angular/core@^10.1.2 but none is installed. You must install peer dependencies yourself.
```
However, everything works fine with on Angular 11, so I think the peer dependencies of angular-google-tag-manager should be updated to also accept Angular 11

**Comment by gcko** [comment]
@TokkeDev Please check https://github.com/mzuccaroli/angular-google-tag-manager/pull/47, I have added support for Angular 11

**Comment by mzuccaroli** [comment]
the release for Angular 11 is ready on branch https://github.com/mzuccaroli/angular-google-tag-manager/tree/feature/angular_11  and is in testing phase, will be released soon 
if you want to contribute to help testing and accelerate the process please contct me ;)

**Comment by gcko** [comment]
Hey Marco,

I can definitely help. Also, Have you looked at the Pull request I sent? It handles some minor changes for tests as well as adding some additional typing.

Best,
Jared M. Scott
Founder | Variable.
+1-562-302-8063
+886-966463236

**Comment by mzuccaroli** [comment]
hi @gcko thank you for the contribution I have merged your PR in the dedicated branch:  https://github.com/mzuccaroli/angular-google-tag-manager/tree/feature/angular_11
the angular version is updated to 11.0.7 and the demo application is updated too, can you help by checking and performe some checks in this branch?

**Comment by TokkeDev** [comment]
Any progress on the Angular 11 support?

**Comment by mzuccaroli** [comment]
The branch Is in testing phase, i hope ti complete the release this week, if you are in hurry you can help by testing the branch

**Comment by TokkeDev** [comment]
That sounds great, I was just wondering. Thanks for a great package @mzuccaroli 😊

**Comment by mzuccaroli** [comment]
@TokkeDev the 1.3.0 release with Angular 11 compatibility is available on npm ;)
