### ISSUE TITLE
Infinite tag triggering given a single dataLayer push

### ISSUE THREAD

**Issue by robertvb** [mzuccaroli/angular-google-tag-manager#48]
Hi guys, thanks for the library. Appreciated.

I have this snippet that I am sure is being called only once: 

`  sendAnalytics(text: string) {
    console.log("calling GTM push")
    const gtmTag = {
      event: 'user_search',
      text: text,
    }
    this.gtmService.pushTag(gtmTag)
  }`

Being 'text' a custom data layer variable previously defined in GTM.

Then, I have created a custom HTML tag: 

`<script>
  console.log("CUSTOM HTML text value: " + {{text}})
  gtag('event', 'user_search', {'event_label': {{text}} });
  fbq('track', 'user_search');
</script>`

With a custom trigger for events containing 'user_search'.

Then, I can see the custom HTML code is being called thousand times before crashing and this.gtmService.pushTag is only called once.

I believe is a quite simple config and I assume it should be only called once.

Could you help?

Thanks.

**Comment by mzuccaroli** [comment]
i think this problem is caused by your GTM configuration, the custom gtm tag it's not strictly related to the library
