### ISSUE TITLE
No Iframe in body tag?

### ISSUE THREAD

**Issue by DK9000** [mzuccaroli/angular-google-tag-manager#49]
The iFrame is not popping up in the body tags? Am i doing something wrong? I did follow the article linked in the NPM.

App.module.ts

`@NgModule({
  declarations: [AppComponent, ParallaxDirective, DropzoneDirective, DocPipe],
  imports: [
    HomeModule,
    HttpClientModule,
    NavsModule,
    AppRoutingModule,
    DeferLoadModule,
    AgmSnazzyInfoWindowModule,
    BrowserModule,
    ToastrModule.forRoot(),
    AngularFireAuthModule,
    AngularFireModule.initializeApp(environment.firebase),
    AngularFirestoreModule,
    AngularFireStorageModule,
    BrowserAnimationsModule,
    Ng2ImgMaxModule,
    ImageCropperModule,

  ],
  providers: [
    CaseService,
    GeoService,
    GeocodeService,
    GoogleMapsAPIWrapper,
    AuthService,
    GoogleAnalyticsServiceService,
    FilterService,
    { provide: "googleTagManagerId", useValue: "MY ID!!!" },
  ],
  bootstrap: [AppComponent],
})

app.component.ts `

` ngAfterViewInit() {
    this.setVideo();
    this.gtmService.addGtmToDom();
  }

  constructor(
    private router: Router,
    private gtmService: GoogleTagManagerService
  ) {

    this.router.events.forEach(item => {
      if (item instanceof NavigationEnd) {
        const gtmTag = {
          event: 'page',
          pageName: item.url
        }
        this.gtmService.pushTag(gtmTag)
      }
    })
  }`

**Comment by gabriel-eguia** [comment]
Same problem here, could you solve this?

**Comment by mzuccaroli** [comment]
can  you try with the new version?

**Comment by DK9000** [comment]
Mine works for some reason. Tag manager is up and running on my site, but the iFrame is not set like in the tutorial, but it  works :)

**Comment by mzuccaroli** [comment]
dont worry the noscript iframe was removed by this commit https://github.com/mzuccaroli/angular-google-tag-manager/commit/a10374cd6bbbd2f47ddedab6bc815320e065a85b#diff-5dda773090c6f399df6ea76b4d916ddcb78c06c2c035ecd49efe93b4dfed55b5
i need to update the tutorial
