### ISSUE TITLE
'ɵɵinject' / 'ɵɵdefineInjectable' not found in '@angular/core'

### ISSUE THREAD

**Issue by fabioaliprandi** [mzuccaroli/angular-google-tag-manager#5]
Hi!
I can' use this library on my Angular Project because I receive these warnings, when I make `ng serve`:

` WARNING in ./node_modules/angular-google-tag-manager/fesm5/angular-google-tag-manager.js
"export 'ɵɵinject' was not found in '@angular/core'`

`WARNING in ./node_modules/angular-google-tag-manager/fesm5/angular-google-tag-manager.js
 "export 'ɵɵdefineInjectable' was not found in '@angular/core'`

It may be that I did something wrong, but I can't understand why.

This is my `tsconfig.json` : 

> {
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

And then, my `package.json` : 

> {
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "@ng-toolkit/universal": "^7.1.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-google-tag-manager": "^1.1.1",
    "chart.js": "^2.8.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "moment": "^2.24.0",
    "ng2-charts": "^2.2.0",
    "ng2-nouislider": "^1.8.2",
    "ng2-pdf-viewer": "^6.0.1",
    "ngx-useful-swiper": "^8.0.1",
    "nouislider": "^13.1.5",
    "rxjs": "^6.0.0",
    "swiper": "^4.5.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@types/swiper": "^4.4.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~3.1.1"
  }
}

**Comment by mzuccaroli** [comment]
Hi, I took a quick look at the error and I think it might depend on Angular version.
take a look to [this issue ](https://github.com/angular/angular/issues/30413)
I have developed the library on angular 7.2 and now I moved to 8. For a quick fix you can try to update your angular libs 
[this site](https://update.angular.io/) is a great resource to keep your angular project up to date ;)

**Comment by fabioaliprandi** [comment]
Is there the possibility of having this library working with angular 7?
Or a minor version of 1.1.1.

I've tried this:

> npm install -S @angular/material @angular/cdk @angular/animations
npm uninstall @angular/core
npm install -S @angular/core

but I received a lot of errors.
can you please help me? I can't find a solution.

**Comment by mzuccaroli** [comment]
you can try with older version the [1.0.1](https://www.npmjs.com/package/angular-google-tag-manager/v/1.0.1) should fit 
the main differences between 1.0 and 1.1 are angular dependencies

**Comment by fabioaliprandi** [comment]
Version 1.0.1 resolves the issue.

But Now I can't manage to see activities on GoogleTagManager/GoogleAnalitycs.
I can see GA activity (and url) only when I refresh the page.
Everytime I change page, I don't see any changes.

On my `ngOnInit()` App Component (as your example):
> this.router.events.forEach(item => {
        if(item instanceof NavigationEnd) {
              console.group('GOOGLE TAG MANAGER');console.log('routing -> ',item);
              console.log('dataLayer -> ', window['dataLayer']);console.groupEnd();
            const gtmTag = {
              event: 'page',
              pageName: item.url
            };
            this.gtmService.pushTag(gtmTag);
        }
      });

for each routing change, window['dataLayer'] updates but I can't see nothing on Chrome - Network developer tools. So, no calls to Google.

Can you help me?

**Comment by mzuccaroli** [comment]
ok I think this is a GTM misconfiguration, the code seems ok but you need your GTM account to push events to analytics take a look to [this tutorial](https://blog.hubspot.com/marketing/google-tag-manager-guide) in section 3 and 4
