### ISSUE TITLE
[Angular Universal] How to use package with different GTM ID?

### ISSUE THREAD

**Issue by MDzyga** [mzuccaroli/angular-google-tag-manager#54]
Hi,
Could you help me with configuration your package when GTM ID comes from API response?

**Comment by mzuccaroli** [comment]
I think this is a tricky situation, do you think is a possible solution to fetch the API duringh the build process and then make the gtm id static?
usually that id is an enviromnent variable

**Comment by MDzyga** [comment]
Unfortunately no, I can solve this without using your package.
When I get GTM ID I can create required tags in HTML using document.createElement('script'|'noscript'). But this solution doesn't allow me to push events

**Comment by mzuccaroli** [comment]
i think that the only solution for your situation is a custom approach, you can take a look to the main funcions of the library in [this file](https://github.com/mzuccaroli/angular-google-tag-manager/blob/master/projects/angular-google-tag-manager/src/lib/angular-google-tag-manager.service.ts) and adapt them to your code, the core of the gtm lib si not so much complicated

**Comment by MDzyga** [comment]
thanks :)
