### ISSUE TITLE
Google Tag Manager Issue with FreshChat Widget

### ISSUE THREAD

**Issue by sharath0033** [mzuccaroli/angular-google-tag-manager#59]
Hi, I am using GTM to inject FreshChat widget into our application.

I have followed the tutorial of integrating the GTM but the FreshChat is not getting triggered. The FreshChat Script is getting injected but not getting triggered.

Please see the below screenshot of the injected script.
![image](https://user-images.githubusercontent.com/15948031/112608333-3600b800-8e40-11eb-8c34-ce98dd2e4f2d.png)

I am using a similar GTM library in my other application(NuxtJs) to inject the same FreshChart widget and it is working fine there. So I ruled out that there might be some issue with my GTM setup.

Please see the below screenshot of the NuxtJs FreshChart script and Initialized widget elements
![image](https://user-images.githubusercontent.com/15948031/112608832-cc34de00-8e40-11eb-84d9-ef93a9371f5e.png)

I haven't tried directly adding GTM to the HTML body. I want to leverage the services provided by this plugin. Let me know if I have to initialize something to trigger the FreshChat script.
 
Thank you

**Comment by mzuccaroli** [comment]
The fresh chat widget is injected by a tag handled by GTM?
in this case, other tags (like analytics) or the datalayer events are working?

**Comment by mzuccaroli** [comment]
close the issue after no reply
