### ISSUE TITLE
Multiple installations of Google Tag Manager detected

### ISSUE THREAD

**Issue by puneetverma05** [mzuccaroli/angular-google-tag-manager#6]
Hey @mzuccaroli , Thanks for the GTM lib it helps a lot,
btw I'm facing the issue I am using **addGtmToDom** in one component to get (Google Linker from GTM) 
and **pushing an Event** on another component
but it injects **multiple GTM scripts** in HTML when I visit any of the pages again
Am I doing something wrong?
PS: I' don't want to inject GTM on all Pages (so not using outside router-outlet)

![multipleGTM](https://user-images.githubusercontent.com/3938044/75987399-dfaf9700-5f15-11ea-8bdf-8d254e2ddd2f.png)

**Comment by puneetverma05** [comment]
A workaround can be if there is no data in dataLayer we can inject gtmToDom else we can skip?
```
const dl = this.gtmService.getDataLayer();
      if(!dl.length) {
      this.gtmService.addGtmToDom();
    }
```

**Comment by mzuccaroli** [comment]
hi @puneetverma05 ,
this library, and google tag manager itself,  find their main use in being present in every page of your site/ application, invoking multiple times the "addGtmToDom" method has the multiple instances as a direct consequence . This is clearly a misuse of the library.

I think the main mistake  is in this phrase: ": I' don't want to inject GTM on all Pages so not using outside router-outlet" , the ideal use is install the GTM service outside the router outlet so you can have a singleton instance of the library (loaded only one time), the main idea is manage tags effects and triggers INSIDE google tag manager  (take a quick look to [this](https://www.analyticsmania.com/post/page-related-variables-and-triggers-in-google-tag-manager/) and [this](https://support.google.com/tagmanager/answer/7679318?hl=en)).
If you need to push specific events  inject  the gtm service to compnents, an then use it like  `this.gtmService.pushTag(gtmTag);` take a look to [my tutorial here](https://itnext.io/how-to-add-google-tag-manager-to-an-angular-application-fc68624386e2)

If you handle google tag manager activation directly inside your code you well need to deploy a new version of the application on every logical change of GTM: **which is a bad idea and one of the problem that GTM itself  fix**: you release one time a single instance of GTM scripts and manage specific GTM logics ad settings inside the GTM console without touching your codebase.
