### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by cpereyra5199** [mzuccaroli/angular-google-tag-manager#62]
When I make an attempt to call the push method.  I get the error below in console.

GET https://www.googletagmanager.com/gtm.js?id=XXXXXXXX net::ERR_ABORTED 404

When I try to navigate to that url directly I also get a 404.  Could you please tell me if I am doing something wrong?

Thank you.

**Comment by cpereyra5199** [comment]
It also looks like the tag is being added each time I refresh the page.

![image](https://user-images.githubusercontent.com/8915559/113485316-e131f280-947a-11eb-9c3f-44e5337935b8.png)

**Comment by GregoireAmeye** [comment]
I just had the same issue. Your comment made me think a little more and I noticed I didn't deploy the GTM property yet.
Did this, and it works now.

**Comment by cpereyra5199** [comment]
What do you mean by "Didn't deploy the GTM property?

**Comment by GregoireAmeye** [comment]
In the Google Tag Manager UI, the submit button on the top right. I guess publish would be a better word for it.

**Comment by cpereyra5199** [comment]
That worked!  Thank you!
