### ISSUE TITLE
Silently Fail if GTM ID is not provided. For unit tests via karma/jasmine

### ISSUE THREAD

**Issue by jonlighthill** [mzuccaroli/angular-google-tag-manager#63]
https://github.com/mzuccaroli/angular-google-tag-manager/blob/68b8849544719337c038ab9a8d0ea9d8241bbe3c/projects/angular-google-tag-manager/src/lib/angular-google-tag-manager.service.ts#L42

Is it possible to add an option to silently fail when a gtmid is not provided? We have a global log service that is using the GoogleTagManagerService to push tags and every component that uses the global logging service and has a unit test requires us to provide the googleTagManagerId. 

 providers: [{ provide: "googleTagManagerId", useValue: "test" }],

**Comment by mzuccaroli** [comment]
If your unit test invoke a global service you have some issues in your tests that are not isolated.
The "throw exception" is the right behavior for the gtm service, that for your project, is an external service.
My advice is to mock or spy all external and global services, take a look at this: https://codecraft.tv/courses/angular/unit-testing/mocks-and-spies/

In your case i suggest that when you are testing your components you need to mock(or spy) your global log services, and wen you test the global service you spy on GTM service. Generally a unit test should never invoke external library, (you are testing your code, not the library)
