### ISSUE TITLE
Support for Multiple GTM Containers on the page

### ISSUE THREAD

**Issue by Mustahsan1** [mzuccaroli/angular-google-tag-manager#66]
Hi,

Is there anyway to use multiple containers on the page as per the official documentation?

https://developers.google.com/tag-manager/devguide#multiple-containers

I am looking for a way to add multiple GTM containers on the page using this library. Any help would be highly appreciated.

Thanks.

**Comment by mzuccaroli** [comment]
hi, in this moment the library doesn't support multiple containers
