### ISSUE TITLE
Support for Angular 12

### ISSUE THREAD

**Issue by TokkeDev** [mzuccaroli/angular-google-tag-manager#77]
angular-google-tag-manager should allow peer dependency of Angular 12. When doing npm install, the following errors appear:

```
npm WARN angular-google-tag-manager@1.3.2 requires a peer of @angular/common@^11.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN angular-google-tag-manager@1.3.2 requires a peer of @angular/core@^11.0.7 but none is installed. You must install peer dependencies yourself.
```

However, as far as I can tell, everything seems to be working fine with on Angular 12, so I think the peer dependencies of angular-google-tag-manager should be updated to also accept Angular 12

**Comment by mzuccaroli** [comment]
version 1.4.0 with angular 12 support is released
