### ISSUE TITLE
Version 1.4.0 still warning about angular 11.0.7 peer

### ISSUE THREAD

**Issue by ascandal** [mzuccaroli/angular-google-tag-manager#83]
Installing with angular 12.0.3.

npm WARN angular-google-tag-manager@1.4.0 requires a peer of @angular/common@^11.0.7 but none is installed. You must install peer dependencies yourself.
npm WARN angular-google-tag-manager@1.4.0 requires a peer of @angular/core@^11.0.7 but none is installed. You must install peer dependencies yourself.

**Comment by mzuccaroli** [comment]
fixed with 1.4.1 version, than you  for reporting the bug ;)
