### ISSUE TITLE
ɵɵdefineInjectable undefined

### ISSUE THREAD

**Issue by FatManiac** [mzuccaroli/angular-google-tag-manager#86]
Hi,

trying to update angular-google-tag-manager, from 0.0.1 to 1.4.2, i get this error

TypeError: undefined is not a function (near '...r["\u0275\u0275defineInjectable"]...')

Coming from line 89 in angular-google-tag-manager.js

If someone ever ended up having this error, i could use a hand :)

**Comment by mzuccaroli** [comment]
Hi, it's  quite a big jump, which version of angular are you using?

**Comment by FatManiac** [comment]
7.2.10

**Comment by mzuccaroli** [comment]
ok the 1.4.x version is for angular 12 you have a quite old version of angular so i think you are stick to the earlier versions of the lib.
Dont worry, the main behavior is not changed so it's save to block your library to early versions.
here the list of alle the versions: https://www.npmjs.com/package/angular-google-tag-manager

**Comment by FatManiac** [comment]
yes but earlier versions don't include https, i litteraly tried them one by one from 0.0.1 up to 1.1.4
![Capture d’écran 2021-06-29 à 10 30 29](https://user-images.githubusercontent.com/7302883/123764526-27092600-d8c5-11eb-9ee6-dc2b37128764.png)

**Comment by FatManiac** [comment]
@mzuccaroli is there a way for me to fork an old version to change the scheme ? I can't find 0.0.1 on the repo

**Comment by mzuccaroli** [comment]
you can try to fork from this commit : https://github.com/mzuccaroli/angular-google-tag-manager/tree/f01602c3bf511702375279c2c19e0b8897199da5

i think is compatible with angular 7
