### ISSUE TITLE
Need to Inject the service or get error: NullInjectorError: No provider for GoogleTagManagerService

### ISSUE THREAD

**Issue by intotecho** [mzuccaroli/angular-google-tag-manager#87]
I installed this today on my Angular 8 project.

I was following both the [blog post](https://itnext.io/how-to-add-google-tag-manager-to-an-angular-application-fc68624386e2) 
and also the readme on npm and the demo project repo. 

I kept getting this error when loading the app. What resolved it was to add the GoogleTagManagerService as a provider. 

This is not shown in any of the user guides - although it does add some other keys to the providers list. 
In AppModule, I have 

```
providers: [
    //...
    GoogleTagManagerService,
    {provide: 'googleTagManagerId',  useValue: 'GTM-WXRQXV6'},
  ]

```

I am not sure if this is due to angular, or something I am doing in my app?

I think this could be resolved by updating the readme and blog by adding the GoogleTagManagerService name to the list of providers. But then I am surprised it has not been reported by others.

**Comment by mzuccaroli** [comment]
8 is a quite old version of Angular, 
the last version of the lib (1.4.x) is based on angular 12, 
for compatibility reasons you can try older versions, you can try 1.1.3 or lower, 
I think I developed the first version of the library with angular 9 so i can't assure you that angular 8 will work
