### ISSUE TITLE
Getting Unresolved depenedencies when updating angulat to version 11.

### ISSUE THREAD

**Issue by nehu92** [mzuccaroli/angular-google-tag-manager#88]
While updating from angular 8 to angular 11. i am getting the following errors.

`91 error code ERESOLVE
92 error ERESOLVE unable to resolve dependency tree
93 error
94 error While resolving: onvation-web@0.0.0
94 error Found: @angular/common@11.2.14
94 error node_modules/@angular/common
94 error   @angular/common@"^11.2.14" from the root project
94 error
94 error Could not resolve dependency:
94 error peer @angular/common@"^12.0.3" from angular-google-tag-manager@1.4.2
94 error node_modules/angular-google-tag-manager
94 error   angular-google-tag-manager@"^1.4.2" from the root project
`

is there an specific version compatible with angular 11?

**Comment by p-harisha** [comment]
"angular-google-tag-manager": "1.3" did the trick :)

**Comment by mzuccaroli** [comment]
yes, the 1.3.X version
you can check all old versions here: https://github.com/mzuccaroli/angular-google-tag-manager/releases
