### ISSUE TITLE
Cross-site Cookie Issue

### ISSUE THREAD

**Issue by all2pie** [mzuccaroli/angular-google-tag-manager#89]
Getting this issue for Google cookies: 

> Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

**Comment by mzuccaroli** [comment]
I think may be depending by someting activate in your gtm tags, you can try by disabling all tags inside your gtm account and see if the error still persists

**Comment by all2pie** [comment]
All the custom tags are activated on click, but this issue occurs on load. 

Found this: [https://stackoverflow.com/a/60882686/11587308](probable-solution)


I can add this in my tags but don't know to to apply it library wide .

**Comment by mzuccaroli** [comment]
closing because probably gtm account misconfiguration
