### ISSUE TITLE
angular 6 its throws error

### ISSUE THREAD

**Issue by RKM001** [mzuccaroli/angular-google-tag-manager#9]
eedefineInjectable, eeInject is not known function.

instead of defineInjectable, inject it will work in angular 6.

can have any version of this package which using defineInjectable,inject

**Comment by mzuccaroli** [comment]
I have developed this library on angular 7.2  so there is not an angular 6.
You can try to use an old library version and try to run it on your project ([this issue can help](https://github.com/mzuccaroli/angular-google-tag-manager/issues/5))

**my advice is to update angular to a more recent version**, it's not a big deal:
[this site](https://update.angular.io/) is a great resource to keep your angular project up to date ;)
